version: '3.8'
services:
    app:
        restart: unless-stopped
        ports:
            - '${APP_PORT:-9000}:80'
        networks:
            - app-network
        healthcheck:
            test: [ "CMD", "curl --fail --connect-timeout 10 http://localhost:${APP_PORT} || exit 1" ]
            interval: 60s
            timeout: 10s
            retries: 3

networks:
    app-network:
        driver: bridge
